name       : python-secretstorage
version    : 3.3.2
release    : 8
source     :
    - https://pypi.io/packages/source/S/SecretStorage/SecretStorage-3.3.2.tar.gz : 0a8eb9645b320881c222e827c26f4cfcf55363e8b374a021981ef886657a912f
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings to Freedesktop.org Secret Service API
description: |
    This module provides a way for securely storing passwords and other secrets. It uses D-Bus Secret Service API that is supported by GNOME Keyring (since version 2.30) and KSecretsService. SecretStorage supports most of the functions provided by Secret Service, including creating and deleting items and collections, editing items, locking and unlocking collections (asynchronous unlocking is also supported).
rundeps    :
    - python-cryptography
    - python-jeepney
build      : |
    %python3_setup
install    : |
    %python3_install
