name       : python-secretstorage
version    : 3.3.1
release    : 6
source     :
    - https://pypi.io/packages/source/S/SecretStorage/SecretStorage-3.3.1.tar.gz : fd666c51a6bf200643495a04abb261f83229dcb6fd8472ec393df7ffc8b6f195
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings to Freedesktop.org Secret Service API
description: |
    This module provides a way for securely storing passwords and other secrets. It uses D-Bus Secret Service API that is supported by GNOME Keyring (since version 2.30) and KSecretsService. SecretStorage supports most of the functions provided by Secret Service, including creating and deleting items and collections, editing items, locking and unlocking collections (asynchronous unlocking is also supported).
rundeps    :
    - python-cryptography
    - python-jeepney
build      : |
    %python3_setup
install    : |
    %python3_install
